export const PrivateTypes = {
    IBreakpointsEventsListener: Symbol.for('IBreakpointsEventsListener'),
    BPRecipeAtLoadedSourceSetter: Symbol.for('BPRecipeAtLoadedSourceSetter'),
    HitCountBreakpointsSetter: Symbol.for('HitCountBreakpointsSetter'),
    SingleBreakpointSetter: Symbol.for('SingleBreakpointSetter'),
    SingleBreakpointSetterForHitCountBreakpoints: Symbol.for('SingleBreakpointSetterForHitCountBreakpoints'),
    SingleBreakpointSetterWithHitCountSupport: Symbol.for('SingleBreakpointSetterWithHitCountSupport'),
    CurrentBPRecipesForSourceRegistry: Symbol.for('CurrentBPRecipesForSourceRegistry'),
    CurrentBPRecipeStatusRetriever: Symbol.for('CurrentBPRecipeStatusRetriever'),
    IBreakpointsUpdater: Symbol.for('IBreakpointsUpdater'),
    BPRecipeStatusCalculator: Symbol.for('BPRecipeStatusCalculator'),
    PauseScriptLoadsToSetBPs: Symbol.for('PauseScriptLoadsToSetBPs'),
    ExistingBPsForJustParsedScriptSetter: Symbol.for('ExistingBPsForJustParsedScriptSetter'),
    BPAtNotLoadedScriptViaHeuristicSetter: Symbol.for('BPAtNotLoadedScriptViaHeuristicSetter'),
    BreakpointsSetForScriptFinder: Symbol.for('BreakpointsSetForScriptFinder'),
    BPRecipesForSourceRetriever: Symbol.for('BPRecipesForSourceRetriever'),
    SourceToScriptMapper: Symbol.for('SourceToScriptMapper'),
    DebuggeeBPRsSetForClientBPRFinder: Symbol.for('DebuggeeBPRsSetForClientBPRFinder'),
};
